### ISSUE TITLE
 Hello, I have a question I want to ask.

### ISSUE THREAD

**Issue by koalasf2** [SonoranRP/cust-gcphone#1]
I use this gcphone
And import your total SQL
But still made a mistake
He has assigned a phone number to the player but cannot write to the database.

**Comment by koalasf2** [comment]
![unknown](https://user-images.githubusercontent.com/54642178/64201161-962bb400-cec0-11e9-863b-411334c1ed75.png)

**Comment by koalasf2** [comment]
i change the sql phone_user_contacts then messagethen is work
but the phone call is not work

**Comment by koalasf2** [comment]
![unknown](https://user-images.githubusercontent.com/54642178/64204675-da22b700-cec8-11e9-9c77-d91cc7b08c09.png)

**Comment by koalasf2** [comment]
please HELP ME

**Comment by Fireant456** [comment]
This version is missing a native. Sorry, but we don't support this as a release. This was just used as repo to help facilitate some bug fixing we were needing to do on local repos.
